### ISSUE TITLE
How to evaluate the ScanNet online test split?

### ISSUE THREAD

**Issue by linhaojia13** [lyqun/FPConv#11]
Hi @lyqun  , I try to evaluate the ScanNet online test split, it seems that running the "test_scannet.sh" with "--mode test"  can't produce the required prediction results. Therefore, I change the fuction "write_to_file". The original function "write_to_file":

`def write_to_file(path, probs):`
    `'''`
    `:param path: path to save predicted label`
    `:param probs: N,22`
    `'''`
    `file_name = path + ('.txt' if args.mode == 'test' else '.npy')`
    `if args.skip_exist and os.path.isfile(file_name):`
`  `  `  `   `  `   `print(' -- file exists, skip', file_name)`
`  `  `  `   `  `   `return`
`    if args.mode == 'test':`
`  `  `  `   `  `   `        predict = np.argmax(probs[:, 1:], axis=1) # pn`
`  `  `  `   `  `   `       predict += 1`
`  `  `  `   `  `   `        predict = class_dict[predict]`
`  `  `  `   `  `   `       np.savetxt(path + '.txt', predict)`
`    else:`
`  `  `  `   `  `   `     np.save(path, probs) `
`    print(' -- save file to ====>', file_name)`

I change the second "if" condition and the saved filename for prediction result to meet the submission requirement, after I change:

`def write_to_file(path, probs):`
    `''' `
    `:param path: path to save predicted label`
    `:param probs: N,22`
    `'''`
    `file_name = path + ('.txt' if args.mode == 'test' else '.npy')`
   `if args.skip_exist and os.path.isfile(file_name):`
`  `  `  `   `  `   `        print(' -- file exists, skip', file_name)`
`  `  `  `   `  `   `        return`
    `if args.mode == 'test' and path.find('_preds') > 0 :`
`  `  `  `   `  `   `        predict = np.argmax(probs[:, 1:], axis=1) # pn`
 `  `  `  `   `  `   `       predict += 1`
 `  `  `  `   `  `   `       predict = class_dict[predict]`
`  `  `  `   `  `   `        np.savetxt(path[:-6] + '.txt', predict, fmt='%d')`
   ` else:`
`  `  `  `   `  `   `        np.save(path, probs)`
   ` print(' -- save file to ====>', file_name)`

When I run the test_scannet.sh again, it generate the '.txt' files as follows:
![2020-09-23 21-36-59屏幕截图](https://user-images.githubusercontent.com/38275612/94020347-690cb500-fde5-11ea-8db6-4f0dc80f7e59.png)

Inside each file, it looks like as follows:
![2020-09-23 21-42-34屏幕截图](https://user-images.githubusercontent.com/38275612/94020645-bc7f0300-fde5-11ea-824f-9806f429d9a7.png)

It seems that these files has meet the submission requirement, but when I zip them and submit, it returns a "Evaluation failed":
![2020-09-23 21-36-23屏幕截图](https://user-images.githubusercontent.com/38275612/94020881-fcde8100-fde5-11ea-8476-b0e347c93dac.png)
 
How can I generate the required submission files?

**Comment by lyqun** [comment]
I have check the code and requirements. It seems like, if you save predictions into .txt by np.savetxt, there will be extra blank line ('\n') in the end of the saved file. I will updated the code immediately. By the way, the tiny version reached 63.4 mIoU on online benchmark testing, with 0.5 mIoU point loss compared with the result reported in our paper. So, we recommend you to use the tiny version instead of the full model (2 days or more for training).

**Comment by linhaojia13** [comment]
Hi @lyqun , thank you for your updation.
By abandoning the function 'np.savetxt', I succeeded submitting the test results. However, the reproduced online mIoU only reached 62.2. I use the checkpoint that performed best (in 235 epoch) during the training process to evaluate the online test split. Should I try to use other checkpoints to find the best checkpoint?

**Comment by lyqun** [comment]
Did you evaluate the best model (epoch 235) on ‘eval’ split? The model (checkpoint) used for online testing is the one that we provided in README.

I think there are 2 possible reasons,

1.  Since we evaluate the model by randomly picking a 2x2 block in each scene for evaluation during training process, which is a rough approximation for whole scene evaluation. So, the ‘best’ model for whole evaluation may locate near the best epoch (epoch 235 for your case). We recommand you to test 2 or more checkpoints near epoch 235 (230, 240, ...), which may bring a better performance.

2. Maybe the tiny version is not stable on this dataset (there exists domain gap between train and test splits), re-training may work.

Furthermore, if you trained the model with smaller batch size (bs 2 and single GPU), the model will suffer 1 or more mIoU point loss on whole scene evaluation.

**Comment by linhaojia13** [comment]
Thank you for your advice! I use single GPU for training in batch size 6. Maybe this experiment configuration results in the mIoU point loss. And I will test 2 or more checkpoints near 235 to find the best checkpoint.
