### ISSUE TITLE
Performance for S3DIS dataset

### ISSUE THREAD

**Issue by Sungmin-Woo** [lyqun/FPConv#7]
Hi, thank you for the great work!

I have tried to train the model with S3DIS dataset, but the best mIoU I got is 0.607 at 82 epoch.
I wanna reproduce the model with 62.7 mIoU.
Can you give some more information to get performance in the paper?
It will be very helpful if I can know how you trained the best model.

**Comment by lyqun** [comment]
Hi, how many GPUs and batchsize did you use to train the model?

**Comment by Sungmin-Woo** [comment]
I trained with 2 RTX Titan GPUs, batchsize of 8 totally, and 100 epochs as you did.

**Comment by lyqun** [comment]
We trained the model for S3DIS with 4 GPUs (Titan Xp) and batchsize of 8 totally. Could you repeat this experiment again, with default settings. If you still cannot reproduce the results, I will check the code later.

Before this, how do you obtain 0.607 at eopch 82, by running ./test_s3dis.sh? or just in training process.

Much thanks.

**Comment by Sungmin-Woo** [comment]
Sorry for the confusion. 
Actually, 0.607 was obtained in training process.
By running test_s3dis.sh, mIoU is 0.616 and mAcc is 0.681.
Can better mIoU be obtained by repeating the experiment again or using bigger max epoch?

**Comment by lyqun** [comment]
I checked the log file, we obtained 0.605 mIoU in training process, and 0.627 in full testing (by running ./test_s3dis.sh) at epoch 60. 

It is recommended that you use other checkpoints to evaluate the model (not the best, epoch 60 or 70 is fine). Due to randomness during training, it may work if you could repeat the experiment again. And in our experiments, 100 epochs are enough for S3DIS.

**Comment by Sungmin-Woo** [comment]
Thanks a lot for your prompt reply!!

Then I'll test with other checkpoints.
